# Generated by Django 6.0.5 on 2026-05-19 01:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('date_booked', models.CharField(max_length=50)),
                ('time_booked', models.CharField(max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed/Paid'), ('FAILED', 'Failed/Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='1:1 Parenting Consultation', max_length=255)),
                ('session_type', models.CharField(default='Private Session', max_length=100)),
                ('duration', models.CharField(default='1 hr', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=25000.0, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('location', models.CharField(default='Online / Digital Session', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_string', models.CharField(max_length=50)),
                ('time_string', models.CharField(max_length=50)),
                ('is_booked', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('date_string', 'time_string')},
            },
        ),
    ]
