# Generated by Django 6.0.5 on 2026-05-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecord',
            name='child_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='child_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='child_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='intake_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='school_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
