# Generated by Django 6.0.5 on 2026-05-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingrecord_child_age_bookingrecord_child_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecord',
            name='google_meet_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='site_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
